### ISSUE TITLE
V*:internal Error while cloning an axios object

### ISSUE THREAD

**Issue by mlibre** [pvorb/clone#115]
Axios produces a very large/complex object of the Request.

When I was trying clone this object, I got `v8:internal errror`.

**Comment by yury-kozlov** [comment]
Probably, you mean this error (V8 engine): `FATAL ERROR: v8::Object::SetInternalField() Internal field out of bounds)`
It happens when clone tries to access some native fields of httpResponse, like connection, socket, etc.
I would be glad to know how to prevent this error too.

**Comment by doublemcz** [comment]
+1 I would say it is necessary to remove socket connections from the object. It happens with MongoDB connection as well.

**Comment by aliclark** [comment]
I've opened a related issue https://github.com/nodejs/node/issues/37369

The bug is triggered on https://github.com/pvorb/clone/blob/6df949a1f2175763319326a4e1c4911a9acbd878/clone.js#L165 because of the assignment `child[i] = `, which attempts to set the 'onread' attribute of the node socket, crashing.

Although the crash is a bug in node, it still could be a bug the fact that it was triggered.

At https://github.com/pvorb/clone/blob/6df949a1f2175763319326a4e1c4911a9acbd878/clone.js#L121 and https://github.com/pvorb/clone/blob/6df949a1f2175763319326a4e1c4911a9acbd878/clone.js#L124 a fresh object is created but using a reference to the original prototype. I *think* in this case the object was a magic Proxy-like object, where assignment of this specific property caused a crash, but in general I think this could crop up with other types of code where the prototype has setter or proxy behaviours.

**Comment by girishghoda** [comment]
@aliclark any fix or temporary hack of this?

**Comment by aliclark** [comment]
> @aliclark any fix or temporary hack of this?

Hi @girishghoda, I believe you just need to remove reference to the node socket from the source object before you perform clone - attempting to clone an internal property of the socket is what causes a crash.

**Comment by mlibre** [comment]
New native feature:
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
